---
title: "organize exposure analysis results into publishabled format"
author: "Xing Song"
date: "05/13/2022"
output: 
  html_document:
    self_contained: yes
---

```{r setup, include=FALSE}
rm(list=ls())

knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  include=FALSE,
  fig.height=10,
  fig.width = 6
)

pacman::p_load(
  survival,
  survminer,
  tidyverse,
  magrittr,
  kableExtra,
  # ggridges,
  gridExtra,
  devtools,
  # forestplot,
  grid,
  forestploter,
  ggrepel,
  ggpubr
  # riskRegression,
  # adjustedCurves
)

source_url("https://raw.githubusercontent.com/sxinger/utils/master/plot_util.R")

path_to_dir<-gsub("/src/R","",getwd())
path_to_datadir<-file.path(path_to_dir,"data")

endpts<-c(
   "ACM"
  ,"MACE"
  ,"MI"
  ,"HF"
  ,"STROKE"
  ,"REVASC"
)

nboots<-1

pap_use<-readRDS(file.path(path_to_datadir,"cpap_exposure_final.rda"))
N<-nrow(pap_use)
```

# unadjusted and adjusted KM

```{r, KM}
# unadjusted KM plot - surv
sfit_obj<-survfit(Surv(DEATH_time,DEATH_status) ~ CPAP_IND, data = pap_use)
risk_tbl<-summary(sfit_obj,times = 365*c(1:5))
km_mort_unadj<-ggsurvplot(
  fit = sfit_obj,
  # pval = TRUE,
  conf.int = TRUE,
  legend.labs=c("wo/ PAP", "w/ PAP"),
  # risk.table = TRUE,
  linetype = "strata",
  break.x.by = 365,
  xlab = "Days", 
  ylab = "Unadjusted Survival Probability")

km_mort_unadj2<-km_mort_unadj$plot +
  geom_vline(xintercept=365*c(1:5),linetype=2)+
  geom_label_repel(
    data=data.frame(
      x=risk_tbl$time,
      y=risk_tbl$surv,
      label=round(risk_tbl$surv,3),
      label_int=paste0(round(risk_tbl$surv,3),"[",round(risk_tbl$lower,3),",",round(risk_tbl$upper,3),"]")),
    aes(x=x,y=y,label=label)) +
    geom_text(aes(x=150, y=0.2, label = "p < 0.0001", fontface=0)
  )

# unadjusted KM plot - MACE
cpap_use2<-pap_use %>% filter(MACE_HIST==0&MACE_time>0)
sfit_obj2<-survfit(Surv(MACE_time,MACE_status) ~ CPAP_IND, data = cpap_use2)
risk_tbl<-summary(sfit_obj2, data = cpap_use2,times = 365*c(1:5))
km_mace_unadj<-ggsurvplot(
  fit = sfit_obj2,
  # pval = TRUE,
  conf.int = TRUE,
  legend.labs=c("wo/ PAP", "w/ PAP"),
  # risk.table = TRUE,
  linetype = "strata",
  break.x.by = 365,
  xlab = "Days", 
  ylab = "Unadjusted MACE-free Probability")

km_mace_unadj2<-km_mace_unadj$plot +
  geom_vline(xintercept=365*c(1:5),linetype=2)+
  geom_label_repel(
    data=data.frame(
      x=risk_tbl$time,
      y=risk_tbl$surv,
      label=round(risk_tbl$surv,3),
      label_int=paste0(round(risk_tbl$surv,3),"[",round(risk_tbl$lower,3),",",round(risk_tbl$upper,3),"]")
    ),
    aes(x=x,y=y,label=label)
  ) +
  geom_text(aes(x=150, y=0.2, label = "p < 0.0001", fontface=0))

# adjusted KM plot - surv
fitcox<-readRDS(file.path(path_to_datadir,"ACM","boot1","coxph_iptw_main.rda"))$fit_cox
pval<-summary(fitcox)$coefficients["CPAP_IND",6]
pred_df<-pap_use %>% select(attr(fitcox$means,"names")) %>% select(-CPAP_IND) %>% unique 
# rep_n<-nrow(pred_df)
# pred_df %<>%
#   mutate(rn = 2) %>%
#   tidyr::uncount(rn) %>%
#   mutate(
#     DEATH_time = rep(365*5,rep_n*2),
#     DEATH_status = rep(1,rep_n*2),
#     CPAP_IND = rep(c(0,1),rep_n)
#   )
sfit0<-summary(survfit(fitcox,newdata=pred_df %>% mutate(CPAP_IND=0),conf.int = T)) # predicted risks
sfit1<-summary(survfit(fitcox,newdata=pred_df %>% mutate(CPAP_IND=1),conf.int = T)) # predicted risks
adjkm_df<-data.frame(
  time = sfit0$time,
  surv = apply(sfit0$surv,1,mean),
  std = apply(sfit0$std.err,1,mean),
  # lower = apply(sfit0$surv,1,function(x) quantile(x,0.025)),
  # upper = apply(sfit0$surv,1,function(x) quantile(x,0.975)),
  CPAP_IND = rep(0,length(sfit0$time))
) %>%
  bind_rows(
    data.frame(
      time = sfit1$time,
      surv = apply(sfit1$surv,1,mean),
      std = apply(sfit1$std.err,1,mean),
      # lower = apply(sfit1$surv,1,function(x) quantile(x,0.025)),
      # upper = apply(sfit1$surv,1,function(x) quantile(x,0.975)),
      CPAP_IND = rep(1,length(sfit0$time))
  )
) %>%
  filter(time > 0) %>%
  mutate(CPAP_IND = as.factor(CPAP_IND),
         lower = surv - 1.96*std,
         upper = surv + 1.96*std)

risk_tbl2<-adjkm_df %>%
  filter(time %in% c(365,730,1095,1460,1825))
  
km_mort_adj<-ggplot(adjkm_df,aes(x=time,y=surv)) +
  geom_step(aes(group=CPAP_IND,color = CPAP_IND),size=2.5) +
  geom_ribbon(aes(fill = CPAP_IND, ymin = lower, ymax = upper)) + 
  geom_vline(xintercept=365*c(1:5),linetype=2) +
  geom_label_repel(
    data=data.frame(
      x=risk_tbl2$time,
      y=risk_tbl2$surv,
      label=round(risk_tbl2$surv,3),
      label_int=paste0(round(risk_tbl2$surv,3),"[",round(risk_tbl2$lower,3),",",round(risk_tbl2$upper,3),"]")),
    aes(x=x,y=y,label=label)
  ) + 
  geom_text(aes(x=170, y=0.2, label = ifelse(pval<0.0001, "p < 0.0001",pval)), fontface=0) +
  scale_x_continuous(breaks = c(0,365,730,1095,1460,1825),
                     labels = c(0,365,730,1095,1460,1825)) +
  ylim(0,1) +  ylab("Adjusted Survival Probability") + xlab("Days") +
  theme_survminer()

# adjusted KM plot - MACE
fitcox<-readRDS(file.path(path_to_datadir,"MACE","boot1","coxph_iptw_main.rda"))$fit_cox
pred_df<-cpap_use2 %>% select(attr(fitcox$means,"names")) %>% select(-CPAP_IND) %>% unique 
pval<-summary(fitcox)$coefficients["CPAP_IND",6]
# rep_n<-nrow(pred_df)
# pred_df %<>%
#   mutate(rn = 2) %>%
#   tidyr::uncount(rn) %>%
#   mutate(
#     MACE_time = rep(365*5,rep_n*2),
#     MACE_status = rep(1,rep_n*2),
#     CPAP_IND = rep(c(0,1),rep_n)
#   )
sfit0<-summary(survfit(fitcox,newdata=pred_df %>% mutate(CPAP_IND=0),conf.int = T)) # predicted risks
sfit1<-summary(survfit(fitcox,newdata=pred_df %>% mutate(CPAP_IND=1),conf.int = T)) # predicted risks
adjkm_df<-data.frame(
  time = sfit0$time,
  surv = apply(sfit0$surv,1,mean),
  std = apply(sfit0$std.err,1,mean),
  # lower = apply(sfit0$surv,1,function(x) quantile(x,0.025)),
  # upper = apply(sfit0$surv,1,function(x) quantile(x,0.975)),
  CPAP_IND = rep(0,length(sfit0$time))
) %>%
  bind_rows(
    data.frame(
      time = sfit1$time,
      surv = apply(sfit1$surv,1,mean),
      std = apply(sfit1$std.err,1,mean),
      # lower = apply(sfit1$surv,1,function(x) quantile(x,0.025)),
      # upper = apply(sfit1$surv,1,function(x) quantile(x,0.975)),
      CPAP_IND = rep(1,length(sfit1$time))
  )
) %>%
  filter(time > 0) %>%
  mutate(CPAP_IND = as.factor(CPAP_IND),
         lower = surv - 1.96*std,
         upper = surv + 1.96*std)

risk_tbl2<-adjkm_df %>%
  filter(time %in% c(365,730,1095,1460,1825))
  
km_mace_adj<-ggplot(adjkm_df,aes(x=time,y=surv)) +
  geom_step(aes(group=CPAP_IND,color = CPAP_IND),size=2.5) +
  geom_ribbon(aes(fill = CPAP_IND, ymin = lower, ymax = upper)) + 
  geom_vline(xintercept=365*c(1:5),linetype=2) +
  geom_label_repel(
    data=data.frame(
      x=risk_tbl2$time,
      y=risk_tbl2$surv,
      label=round(risk_tbl2$surv,3),
      label_int=paste0(round(risk_tbl2$surv,3),"[",round(risk_tbl2$lower,3),",",round(risk_tbl2$upper,3),"]")),
    aes(x=x,y=y,label=label)) + 
  geom_text(aes(x=170, y=0.2, label = ifelse(pval<0.0001, "p < 0.0001",pval)), fontface=0) +
  scale_x_continuous(breaks = c(0, 365,730,1095,1460,1825),
                     labels = c(0, 365,730,1095,1460,1825)) +
  ylim(0,1) +  ylab("Adjusted MACE-free Probability") + xlab("Days") +
  theme_survminer()

# put the plots together
kmplot<-ggarrange(
     km_mort_unadj2
    ,km_mort_adj
    ,km_mace_unadj2
    ,km_mace_adj
    ,ncol = 2,nrow = 2
    ,common.legend = TRUE, legend="bottom"
)
# kmplot
# save figure
ggsave(
  file.path(path_to_dir,"res","cpap_expo_on_surv_km.tiff"),
  plot = kmplot,
  dpi = 300,
  width = 12, 
  height = 7, 
  units = "in",
  device = 'tiff'
)
```


# visualize exposure effects based on main-effect models

```{r, main_effect, include = TRUE}
dat<-c()
for(endpt_i in endpts){
  # endpt_i<-endpts[2]
  # boot_i<-1
  adh_df<-c()
  for(boot_i in 1:nboots){
    # whole-data model
    #--main-effect
    boot<-readRDS(
      file.path(path_to_datadir,endpt_i,paste0("boot",boot_i),
                "coxph_iptw_main.rda"))[["fit_cox"]]
    adh_df %<>%
        bind_rows(
          data.frame(summary(boot)$coefficients) %>%
            cbind(data.frame(confint(boot))) %>%
            rownames_to_column(var = "vari") %>%
            filter(grepl("CPAP_IND",vari)) %>%
            gather(summ_var,summ_val,-vari) %>%
            dplyr::filter(summ_var %in% c("coef","X2.5..","X97.5..","Pr...z..")) %>%
            mutate(model = "main",
                   stratum_var = "None",
                   stratum_val = " ")
      )

    # stratified model
    #--main-effect
    boot<-readRDS(
      file.path(path_to_datadir,endpt_i,paste0("boot",boot_i),
                "coxph_strata_main.rda")) %>% as.data.frame()
    adh_df %<>%
        bind_rows(
          boot %>%
            mutate(
              vari = fit_var,
              coef = as.numeric(coef),
              `se(coef)` = as.numeric(`se(coef)`),
              `Pr...z..` = `Pr(>|z|)`
            ) %>%
            filter(grepl("CPAP_IND",vari)) %>%
            mutate(
              `X2.5..`= coef - 1.96*`se(coef)`,
              `X97.5..`= coef + 1.96*`se(coef)`
            ) %>%
            gather(summ_var,summ_val,-vari,-stratum_var,-stratum_val) %>%
            dplyr::filter(summ_var %in% c("coef","X2.5..","X97.5..","Pr...z..")) %>%
            mutate(summ_val = as.numeric(summ_val),
                   model = "main")
      )
  }
  dat %<>%
    dplyr::bind_rows(
          adh_df %>%
            dplyr::group_by(stratum_var,stratum_val,model,vari,summ_var) %>%
            dplyr::summarize(summ_val_mu=mean(summ_val),
                             summ_val_sd=sd(summ_val),
                             .groups = "drop") %>%
            dplyr::mutate(endpt = endpt_i)
    )
}

dat %<>%
  pivot_wider(
          id_cols = c("endpt","stratum_var","stratum_val","model","vari"),
          names_from = "summ_var",
          values_from = "summ_val_mu"
        )
colnames(dat)<-c("endpt","stratum_var","stratum_val","model","vari","pval","ci_lb","ci_ub","coef")

dat %<>%
  # fit forestplot default keys
  dplyr::mutate(
    pvallabel = case_when(
      pval < 0.001 ~ "<0.001",
      TRUE ~ as.character(round(pval,3))
    ),
    mean = exp(coef),
    lower = exp(ci_lb),
    upper = exp(ci_ub)
  )
```


```{r, viz_main_effect, fig.width=12, include = TRUE}
dat %<>%
  mutate(
    stratum_var_lbl = recode(
      stratum_var,
      "None" = "01.None",
      "AGEGRP" = "02.Age",
      "SEX" = "03.Sex",
      "RACE_LABEL" = "04.Race",
      "LIS_DUAL_IND" = "05.Low-income-subsidy/Dual Eligibility",
      "HYSM" = "06.Hypersomnia",
      "INSM" = "07.Insomina",
      "MACE_HIST" = "08.MACE History",
      "OBES" = "09.Obesity",
      "COPD" = "10.COPD",
      "HTN" = "11.Hypertension",
      "T2DM" = "12.T2DM", 
      "ND" = "13.Neurodic Disorder",
      "AFIB" = "14.Atrial Fibrilation",
      "CCI_CLASS" = "15.Charlson Comorbidity Index",
      "ACG" = "16.Anti-coagulant",
      "AHT" = "17.Anti-hypertensive",
      "ALP" = "18.Anti-lipemic",
      "BGR" = "19.Blood glucose regulator",
      
    ),
    stratum_val_lbl = recode(
      stratum_val,
      "agegrp1" = "65-69 years",
      "agegrp2" = "70-74 years",
      "agegrp3" = "75-79 years",
      "agegrp4" = "80+ years",
      "0" = "No",
      "1" = "Yes",
      " " = " ",
      "AA" = "Black",
      "AI" = "Native American",
      "Asian" = "Asian",
      "Other" = "Other",
      "Unknown" = "Unknown",
      "White" = "White",
      "F" = "Female",
      "M" = "Male"
    ),
    endpt_lbl = endpt
  )

fplt1<-forestplot.HR(
  df = dat %>% 
    filter(
      endpt %in% c("ACM","MACE") & 
      model =="main" & 
      grepl("^(0[1-9])+",stratum_var_lbl)
    ),  # long table
  x_idx1="stratum_var_lbl", # 1st layer index
  x_idx2="stratum_val_lbl", # 2nd layer index
  y_idx="endpt_lbl", # 1st layer y index
  est="mean", # estimates
  lower="lower", # 95% CI lower bound
  upper="upper", # 95% CI upper bound
  pval="pval", # p value
  plt_par = list(
    xlim = rep(list(c(0, 1.4)),2),
    vert_line = rep(list(c(0.3, 1.2)),2),
    ticks_at = rep(list(c(0.1, 0.5, 1, 1.2)),2)
  ), 
  ny = 2, # number of y groups (must be the same as groups of y_idx)
  idx_display = "Stratification",
)
# save figure
ggsave(
  file.path(path_to_dir,"res","cpap_expo_on_surv_mace_p1.tiff"),
  plot = fplt1,
  dpi = 150,
  width = 12, 
  height = 12, 
  units = "in",
  device = "tiff"
)

fplt2<-forestplot.HR(
  df = dat %>% 
    filter(
      endpt %in% c("ACM","MACE") & 
      model =="main" & 
      !grepl("^(0[1-9])+",stratum_var_lbl)
    ),  # long table
  x_idx1="stratum_var_lbl", # 1st layer index
  x_idx2="stratum_val_lbl", # 2nd layer index
  y_idx="endpt_lbl", # 1st layer y index
  est="mean", # estimates
  lower="lower", # 95% CI lower bound
  upper="upper", # 95% CI upper bound
  pval="pval", # p value
  plt_par = list(
    xlim = rep(list(c(0, 1.4)),2),
    vert_line = rep(list(c(0.3, 1.2)),2),
    ticks_at = rep(list(c(0.1, 0.5, 1, 1.2)),2)
  ), 
  ny = 2, # number of y groups (must be the same as groups of y_idx)
  idx_display = "Stratification",
)
# save figure
ggsave(
  file.path(path_to_dir,"res","cpap_expo_on_surv_mace_p2.tiff"),
  plot = fplt2,
  dpi = 150,
  width = 12, 
  height = 12, 
  units = "in",
  device = "tiff"
)
```


```{r, viz_whole_dat_adh_effect_mace, fig.width=12, include = TRUE}
fplt1<-forestplot.HR(
  df = dat %>% 
    filter(
      !endpt %in% c("ACM","MACE") &
       grepl("^(0[1-9])+",stratum_var_lbl)
    ),  # long table
  x_idx1="stratum_var_lbl", # 1st layer index
  x_idx2="stratum_val_lbl", # 2nd layer index
  y_idx="endpt_lbl", # 1st layer y index
  est="mean", # estimates
  lower="lower", # 95% CI lower bound
  upper="upper", # 95% CI upper bound
  pval="pval", # p value
  plt_par = list(
    xlim = rep(list(c(0, 1.4)),4),
    vert_line = rep(list(c(0.3, 1.2)),4),
    ticks_at = rep(list(c(0.1, 0.5, 1, 1.2)),4)
  ), 
  ny = 4, # number of y groups (must be the same as groups of y_idx)
  idx_display = "Stratification",
)
# save figure
ggsave(
  file.path(path_to_dir,"res","cpap_expo_on_mace_events_p1.tiff"),
  plot = fplt1,
  dpi = 150,
  width = 20,
  height = 12, 
  units = "in",
  device = "tiff"
)

fplt2<-forestplot.HR(
  df = dat %>% 
    filter(
      !endpt %in% c("ACM","MACE") &
      !grepl("^(0[1-9])+",stratum_var_lbl)
    ),  # long table
  x_idx1="stratum_var_lbl", # 1st layer index
  x_idx2="stratum_val_lbl", # 2nd layer index
  y_idx="endpt_lbl", # 1st layer y index
  est="mean", # estimates
  lower="lower", # 95% CI lower bound
  upper="upper", # 95% CI upper bound
  pval="pval", # p value
  plt_par = list(
    xlim = rep(list(c(0, 1.4)),4),
    vert_line = rep(list(c(0.3, 1.2)),4),
    ticks_at = rep(list(c(0.1, 0.5, 1, 1.2)),4)
  ), 
  ny = 4, # number of y groups (must be the same as groups of y_idx)
  idx_display = "Stratification",
)
# save figure
ggsave(
  file.path(path_to_dir,"res","cpap_expo_on_mace_events_p2.tiff"),
  plot = fplt2,
  dpi = 150,
  width = 20,
  height = 12, 
  units = "in",
  device = "tiff"
)
```


```{r}
write.csv(dat,file=file.path(path_to_dir,"res","cpap_expo_all_results.csv"))

```
